travis:
  secure:
    BINSTAR_TOKEN: oOvbv1EqD77pjDzcYJrXg1Mws/gHlV24GG2cUnVX9A0iV/6bOvuVE+Khih71/vQrAygUsM++QU9RCVq3uq2E9YDYg31MqqyIX6pOz3ZJ9KCneCBTVxXPx9NlQNNj3YYp+QrHgHwrlXGLs5oBZSG+ckR9uyZXkX6mi9ebGI4pIgPjC0LgQsewzvE7RALqjGpgZUBVzRAhsfyEh0xOgjKawyOCZnHsrUSu03bVhO8RzeL20qxRWzSI4/VUWRaOSRb+ah5U8OzCjCNfMUNwittxRFL73V4leV73DckoZNK17nSQCQsK6H82lyZYec0sIR/oVzK6geC9mk2UYxLyxYccRaERbLlTojrvrbtsl/oPtfGkTj+HwWFooGJ6vL5MtqhygtPs0LMjf/laI3ZmGyfHOHuMfHz4cWhy3BeMo+S+XGgF/tZw9f2jfY7InrqzLXeysQLixqIhgIcKKT0D4zK/MP3h4wi1aCKnBVZ4XnqRHHPOm+bqVDeOopYscAzL2TVdS97P61TexUWohBpPWLY6K8/8neyrRzMNF3RCMWvQF56HaTCrGaSJJwk2FgcWUauy/0bXgKIVGLAtIDPtliUn9PzK8ZAh8dlpG5mmGze+qmQZcX00KoTS4GNDsIVLwyG4L1YJpmhovtkqdR2wN6adgtOlIXAA5XgnLmQm4whv1/o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
