travis:
  secure:
    BINSTAR_TOKEN: ipz/fn3l2ny51UDji+Kq4rT6kpKTg46T9Kzb9yMMsW/FTtoh4pKDeyUTzOtmdl8b1ZNL0wQ32fyopgylTZy3ZgJnqP22lKp9cdmiH6LelorCHBZgHB1BnlP1MVSrSokUpWn8FpWnCgKtDXPbQaoCOCer/HdtbF23/i1LWhwQIgmFLBg/knq5DzUc2EAZutBSW+aEMf5go9m943lgnHOlIaKwKbXFTrTeGfa2QFcEog+HoC8QAblCTpCIWeJQb60hAM67GtnabAqsrmU2Eaq8n9uuT8X7aJCok9ToBGcqfRgy9OJ0ODrvAShh4K7Bblhv9NmHmShiEoGARkziqC0L/fKmgWmnSTblXtFOHsOIj/msCZToJqdVDDY8U5xGKClGBNXjpbiv9h62uIh+XpBrIIhK+rcicl6Mw5A5FroTsh3OFd69J0aj04ZjeYzQA8BV99KaVN6hAHtXNHdmzRhqfHGK++5JYXBT7//EfEoosidksaZBypCE6VK/SjhWiRbi8o0gS2nVpDai/ArA5xqI7n4qOSh80+NB7rD8jcyBJNdJ/2AoVRcyQVvxxZVgxHesI9zBgef7ctwe81H0yLmwlctH27XcJVqSQbKOyQPcMdTC3okARRfyXD5EwWxsqk9lS0GfXjpByo2s4b1rlZcTSGQBb7QgawXY394AJF7yoOg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
